# Generated by Django 4.2.5 on 2023-10-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("server", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="server",
            old_name="members",
            new_name="member",
        ),
        migrations.AlterField(
            model_name="server",
            name="description",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
